name: Generate Changelog

on:
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6

    - name: Install github_changelog_generator
      run: gem install github_changelog_generator

    - name: Generate Changelog
      run: github_changelog_generator -u michymono77 -p commit-msg-ai
