name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3 # Specify the Ruby version your gem uses
          bundler-cache: true # Caches 'bundle install'

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec tests
        run: bundle exec rspec
