name: Auto Tag on Push

on:
  push:
    branches:
      - master  # Trigger only on the master branch

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Gem Version
      id: get_version
      run: |
        # Extract version directly from the version file
        VERSION=$(grep -Eo 'VERSION\s*=\s*["'"'"'][0-9]+\.[0-9]+\.[0-9]+["'"'"']' lib/commit_msg_ai/version.rb | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
        echo "Gem version: $VERSION"
        echo "::set-output name=tag::v$VERSION"

    - name: Create Tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag ${{ steps.get_version.outputs.tag }}
        git push origin ${{ steps.get_version.outputs.tag }}
